version: "3.9"

services:
  calendly_worker:
    image: calendly-image:latest
    build: .

    container_name: calendly_worker

    restart: unless-stopped

    command: pnpm dev:worker

    depends_on:
      postgres_db:
        condition: service_healthy
      temporal:
        condition: service_started

    volumes:
      - .:/app/calendly_backend
      - calendly-node-modules:/app/calendly_backend/node_modules

    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:password123@postgres_db:5432/calendly_db
      NODE_ENV: development
      SLOT_GENERATION_DAYS: 30
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_NAMESPACE: default
      TEMPORAL_TASK_QUEUE: calendly-tasks

    networks:
      - network_bridge

  temporal:
    container_name: temporal_server
    restart: unless-stopped
    image: temporalio/auto-setup:1.25.2
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PWD: password123
      POSTGRES_SEEDS: postgres_db
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicConfig/development-sql.yaml
    ports:
      - "7233:7233"
    volumes:
      - ./temporal/dynamicConfig:/etc/temporal/config/dynamicConfig
    networks:
      - network_bridge

  temporal-ui:
    container_name: temporal_ui
    restart: unless-stopped
    image: temporalio/ui:2.31.2
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000,http://localhost:5173
    ports:
      - "8080:8080"
    networks:
      - network_bridge

  postgres_db:
    image: postgres:17
    restart: unless-stopped
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: calendly_db

    ports:
      - "5433:5432"

    networks:
      - network_bridge
    
    volumes:
      - postgres_data:/var/lib/postgresql/data


  Calendly_backend_container:
    image: calendly-image:latest
    restart: unless-stopped
    build: .

    container_name: Calendly_backend_container
    depends_on:
      postgres_db:
        condition: service_healthy
      temporal:
        condition: service_started

    ports:
      - "3001:3001"
      - "5555:5555"

    volumes:
      - .:/app/calendly_backend
      - calendly-node-modules:/app/calendly_backend/node_modules

    networks:
      - network_bridge


networks:
  network_bridge:
    driver: bridge


volumes:
  postgres_data:
  calendly-node-modules:

